### PR TITLE
Syntax proposal

### LINKED ISSUE #12: Syntax - considerations
As I understood, you are indeed creating another syntax for stylesheets. Although I consider this might be justifiable, we have to keep in mind some problems it brings:
- Editors are not prepared to your expressions;
- Preprocessors will have a hard time compiling it.

I'm sure there more issues that can be brought up on this topic. Therefore, unless we plan on building plugins for a considerable amount of editors and preprocessors and syntax highlighters or whatever, we should address the possibility of rethinking the syntax to be CSS compliant somehow.

 I'm not here to bring you some solution anyway. But I would like to show an example of things that could be build using compliant syntax. For instance, the code below would fail to compile using Sass:

``` css
foo {
  bar: ||mouseY-25||px;
}
```

whilst the following would get properly compiled:

``` css
foo {
  bar: dss("mouseY|px");
}
```

Again, just an example of something that works. We should definitely discuss more on the topic before defining any syntax or pattern to go forward with.

### PR DESCRIPTION
**Pull request by felipegtx**
Maybe closes #12

### CODE REVIEW

**Comment by guisouza** [comment]
@fernandofleury  take a look

**Comment by guisouza** [comment]
screen shot 2015-09-23 at 7 13 50 pm

**Comment by fernandofleury** [comment]
@guisouza This way you will prevent the FOUC providing default values and overriding then once the code is ready to run. It fixes the "problem", thou I'm not sure it's the "best" way of doing it... You would provide a value just to layout thrash it right over. I know I'm not providing any insight through this, but I'm trying to think of something lighter to work with.

**Comment by guisouza** [comment]
@fernandofleury, @felipegtx  tks for your time and attention. Im on it !

**Comment by felipegtx** [comment]
I've just pushed another sample [here](http://felipegtx.github.io/dss/example/dss2.html) in case you need to see it working with a _slightly_ more complex scenario. (also for the fun of it)

**Comment by guisouza** [comment]
@felipegtx, this example could be made with the exactly same behaviour using the current syntax ..  
I hate to take decisions based on gut feelings ..  
But it is very hard to swallow the verbosity of  *-dss property syntax 
=[

**Comment by felipegtx** [comment]
@guisouza The idea behind my changes was to prove that you didn't need to change much to allow a - IMHO - better an cleaner syntax and still be able to accomplish all that was supposed to work in the current model.

As I said before, I do **NOT** like the current syntax model that - to me - means nothing and corrupts the code with _placeholders_ for a parser that _eventually_ goes around and actually turns it into a valid code. 

Also, the _pipe syntax_ (or any other _'value corruption'_ approach) implies that you will have an invalid document - maybe totally invalid - being loaded by the browser just to serve as a template in the future. I **really** dislike this idea. 

Also I do not agree with the term _verbose_ in this case. I think that it allows anyone that does know CSS to became a DSS programmer while still being able to use whatever IDE/compiler he/she finds fits. It's clearer to read and easier to learn.

With all that said, the beauty of OSS is that we do not need to agree on a single pattern/approach. DSS  is your child and you need to take care of it. I totally understand that you're free to decline PRs such as this to keep the cohesion of what you imagine/plan to the future of the lib! please fell free to decide on what you think is better and, ping me if you want to discuss anything further!

Keep it up! :D

**Comment by guisouza** [comment]
6d6adc48042f6f7b5b403639766628c03e82489e
two new flavours were added, I hope you like it ..  
:heart: :octocat:

**Pull request closed without merging**
